import { useState, useEffect } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useCart } from "@/contexts/CartContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { Loader2, ArrowLeft } from "lucide-react";

export default function StoreCheckout() {
  const { slug } = useParams();
  const navigate = useNavigate();
  const { items, total, clearCart } = useCart();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [tenant, setTenant] = useState<any>(null);
  const [settings, setSettings] = useState<any>(null);
  const [form, setForm] = useState({ name: "", phone: "", address: "", notes: "" });

  useEffect(() => {
    const fetchTenant = async () => {
      const { data } = await supabase.from("tenants").select("*").eq("slug", slug).single();
      if (data) {
        setTenant(data);
        const { data: s } = await supabase.from("settings").select("*").eq("tenant_id", data.id).maybeSingle();
        setSettings(s);
      }
    };
    fetchTenant();
  }, [slug]);

  const deliveryFee = Number(settings?.delivery_fee || 0);
  const grandTotal = total + deliveryFee;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!form.name || !form.phone || !form.address) {
      toast({ title: "Preencha todos os campos", variant: "destructive" });
      return;
    }
    if (!tenant) return;
    setLoading(true);

    try {
      // Create customer
      const { data: customer, error: customerError } = await supabase
        .from("customers")
        .insert({
          tenant_id: tenant.id,
          name: form.name,
          phone: form.phone,
          address: form.address
        })
        .select()
        .single();

      if (customerError) throw customerError;

      // Create order - code is auto-generated by trigger
      const { data: order, error: orderError } = await supabase
        .from("orders")
        .insert({
          tenant_id: tenant.id,
          customer_id: customer?.id,
          channel: "WEB" as const,
          subtotal: total,
          delivery: deliveryFee,
          total: grandTotal,
          notes: form.notes || null,
          code: "" // Will be overwritten by trigger
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      if (order) {
        const orderItems = items.map(i => ({
          order_id: order.id,
          product_id: i.id,
          product_name: i.name,
          qty: i.quantity,
          unit_price: i.price,
          total: i.price * i.quantity
        }));

        await supabase.from("order_items").insert(orderItems);
        
        clearCart();
        navigate(`/r/${slug}/confirmation/${order.code}`);
      }
    } catch (error: any) {
      toast({ title: "Erro ao criar pedido", description: error.message, variant: "destructive" });
    }
    
    setLoading(false);
  };

  if (items.length === 0) {
    return (
      <div className="min-h-screen bg-background flex flex-col items-center justify-center p-4">
        <h2 className="text-xl font-semibold mb-4">Seu carrinho está vazio</h2>
        <Link to={`/r/${slug}`}><Button>Ver Cardápio</Button></Link>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-50 glass border-b">
        <div className="container py-4 flex items-center gap-4">
          <Link to={`/r/${slug}/cart`}>
            <Button variant="ghost" size="icon"><ArrowLeft /></Button>
          </Link>
          <h1 className="text-xl font-bold">Finalizar Pedido</h1>
        </div>
      </header>
      
      <form onSubmit={handleSubmit} className="container py-6 space-y-4 max-w-md">
        <div>
          <Label>Nome *</Label>
          <Input 
            value={form.name} 
            onChange={e => setForm({...form, name: e.target.value})} 
            placeholder="Seu nome completo"
            required 
          />
        </div>
        <div>
          <Label>Telefone *</Label>
          <Input 
            value={form.phone} 
            onChange={e => setForm({...form, phone: e.target.value})} 
            placeholder="(11) 99999-9999"
            required 
          />
        </div>
        <div>
          <Label>Endereço *</Label>
          <Input 
            value={form.address} 
            onChange={e => setForm({...form, address: e.target.value})} 
            placeholder="Rua, número, bairro"
            required 
          />
        </div>
        <div>
          <Label>Observações</Label>
          <Textarea 
            value={form.notes} 
            onChange={e => setForm({...form, notes: e.target.value})} 
            placeholder="Troco, complemento, etc."
          />
        </div>
        
        <div className="bg-card rounded-xl border p-4 space-y-2">
          <h3 className="font-semibold mb-2">Resumo</h3>
          {items.map(item => (
            <div key={item.id} className="flex justify-between text-sm">
              <span>{item.quantity}x {item.name}</span>
              <span>R$ {(item.price * item.quantity).toFixed(2)}</span>
            </div>
          ))}
          <div className="border-t pt-2 mt-2">
            <div className="flex justify-between">
              <span>Subtotal</span>
              <span>R$ {total.toFixed(2)}</span>
            </div>
            <div className="flex justify-between">
              <span>Entrega</span>
              <span>R$ {deliveryFee.toFixed(2)}</span>
            </div>
            <div className="flex justify-between font-bold text-lg mt-2">
              <span>Total</span>
              <span className="text-primary">R$ {grandTotal.toFixed(2)}</span>
            </div>
          </div>
        </div>
        
        <Button type="submit" disabled={loading} className="w-full gradient-primary">
          {loading ? <Loader2 className="animate-spin mr-2 w-4 h-4" /> : null}
          {loading ? "Enviando..." : "Enviar Pedido"}
        </Button>
      </form>
    </div>
  );
}
